### ISSUE TITLE
Charts on dashboard view do not update

### ISSUE THREAD

**Issue by tsteiner4** [fitness-challenge-website/fitnesschallengeapp#16]
**Description:** After adding activities, the dashboard charts do not get updated.
  It would be nice to have activity data displayed to the user on this screen.
  **Severity:** Major

**Comment by jreimer107** [comment]
The UserDash loads is data with ComponentDidMount, and shares no interaction with the AddActivity component that updates the database.

Either we have to elevate the function to App.js (gross) or we need to somehow tell UserDash that its data has changed through the database connection. Maybe axios supports listeners?

**Comment by jreimer107** [comment]
This was actually a bug with how the last day in the chart (today) was being populated. Fix incoming.
