### ISSUE TITLE
Cannot delete account

### ISSUE THREAD

**Issue by ejshumaker** [fitness-challenge-website/fitnesschallengeapp#21]
**Description:** An error is displayed when attempting to delete an account.
 **Severity:** Critical
![DeleteAccountBug](https://user-images.githubusercontent.com/25969157/56623179-c7ce6d80-65f8-11e9-9555-f92cd5a02d49.png)

**Comment by jkaplinsky1** [comment]
Issue resolved. Reauthentication reading null value, reimplemented authentication specifically for deleting account.
