### ISSUE TITLE
Upon updating password and avatar, redirected to empty page with no navigation

### ISSUE THREAD

**Issue by eschirtz** [fitness-challenge-website/fitnesschallengeapp#7]
This was reproduced a few times. There is no way to get out of the empty page without using the back button until the login screen is reached. The avatar never gets updated in any case.
**Severity: Major**

**Comment by jkaplinsky1** [comment]
Issue with avatar updating fixed.

**Comment by jkaplinsky1** [comment]
Fixed issue related to redirecting to empty page.
